[package]
name = "pushr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive", "env"] }
derive_more = { version = "1.0.0", features = ["from"] }
reqwest = "0.12.12"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
